scan_topic: '/scan'
# drive_topic: '/drive'
drive_topic: '/vesc/ackermann_cmd_mux/input/navigation'
safety_topic: '/vesc/low_level/ackermann_cmd_mux/input/safety'
stopping_scale: 0.5 #potentially need for safety controller